### PR TITLE
Allow for definition and prevent redefinition if EMPTY_HASH constant …

### LINKED ISSUE #3: Redefinition of ActionController::Parameters::EMPTY_HASH in gem
/gems/gems/moderate_parameters-0.1.0/lib/moderate_parameters/moderate_parameters.rb:37: warning: already initialized constant ActionController::Parameters::EMPTY_HASH
/gems/gems/actionpack-5.1.7/lib/action_controller/metal/strong_parameters.rb:926: warning: previous definition of EMPTY_HASH was here

### PR DESCRIPTION
**Pull request by tjchambers**
…exists.

Fixes #3

### CODE REVIEW

**Comment by tjchambers** [comment]
Why do my tests have no config?

**Comment by nvick** [comment]
It looks like PR #2 has all the CircleCI config in it.

**Comment by tjchambers** [comment]
wonderful - will wait till it merges.

**Comment by tjchambers** [comment]
Ok - now runs specs!

**Pull request merged**
